name = "BitsX"
uuid = "d1730f61-8521-49b5-9a1a-56a32d208dc4"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.2.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"

[compat]
BitIntegers = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
