name = "BitsX"
uuid = "d1730f61-8521-49b5-9a1a-56a32d208dc4"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Bits = "1654ce90-6ed3-553a-957f-9452c3a40996"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
